### ISSUE TITLE
Tomada de Decisões

### ISSUE THREAD

**Issue by AnotherOne07** [ladata-ufs/onboarding-projetos-G2#2]
Qual metodologia será adotada ?
Quais as atividades que devem ser realizadas para atingir o nosso objetivo principal ?
Qual a divisão de tarefas para os membros da equipe ?

**Comment by maic0w** [comment]
Decidir Tópicos de Pesquisa (objetivos)

Objetivos:
O1 - Qual a raridade por geração (pokemons lendários) ?
O2 - Quais são os atributos comuns em pokemons mais fortes ?
O3 - Qual a relação entre o tamanho e os atributos de poder ?
O4 - É possível identificar uma tendência que relaciona o gênero e força efetiva do pokemon ?

Apêndice:
A1 - Qual o dream team de atributos e habilidades ? (Identificar quais sao as caracteristicas que os pokemons de uma party devem ter para ser um time balanceado)
